In [11]:
import pandas as pd

data = pd.read_csv('data/data_3dcp_winter_filtered.csv')
data = data.drop(['pallet', 'run', 'replicate'], axis=1)
data = data[data['layer_width'] != -1]

data

      layer_height  extrusion  speed  layer_width  over-under
10               8          2     80         49.0           1
11               8          2     80         48.3           1
12               8          2     80         48.4           1
13               8          2     80         48.8           1
14               8          2     80         48.4           1
...            ...        ...    ...          ...         ...
1135             5          2    400         17.4          -1
1136             5          2    400         17.8          -1
1137             5          2    400         17.4          -1
1138             5          2    400         18.1          -1
1139             5          2    400         17.7          -1

[640 rows x 5 columns]

In [12]:
data.to_csv('data/data_3dcp_wClean.csv', index=False)